### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by JAremko** [zhangpeihao/log#1]
Looks like the code has a typo https://github.com/zhangpeihao/log/blob/master/log.go#L66

**Comment by zhangpeihao** [comment]
The number between project name and date is a sequence number to identify the log file.  I have a log process tool to merge log files by day.

**Comment by JAremko** [comment]
Hm. I was thinking it should `fileBeginTime := int(now.Unix() - int64(fileSplitTime))` instead of `fileBeginTime := int(now.Unix() / int64(fileSplitTime))` It looks like we can get division by zero here.

**Comment by zhangpeihao** [comment]
I append some codes to check the fileSplitTime.

Thanks
